class AuthProvider(Protocol):
    """Technology-agnostic auth interface."""
    async def get_user(self, token: str) -> User | None: ...
    async def verify_session(self, session_token: str) -> Session | None: ...
    async def refresh_session(self, refresh_token: str) -> Session | None: ...
    async def sign_out(self, session_token: str) -> None: ...

class UserRepository(Protocol):
    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def update(self, user: User) -> None: ...

class OrganizationRepository(Protocol):
    async def get_by_id(self, org_id: UUID) -> Organization | None: ...
    async def get_by_slug(self, slug: str) -> Organization | None: ...
    async def get_user_organizations(self, user_id: UUID) -> list[Organization]: ...
    async def create(self, org: Organization) -> Organization: ...
    async def add_member(self, membership: Membership) -> None: ...
    async def remove_member(self, org_id: UUID, user_id: UUID) -> None: ...
    async def get_members(self, org_id: UUID) -> list[Membership]: ...